name: Meson Build
author: BSFishy
description: Run a Meson task during your Actions workflow
runs: jobs using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down'
  color: 'green'
inputs:
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v1
  - uses: BSFishy/meson-build@v1.0.3
    with:
      action: test
      directory: build
      setup-options: -Db_coverage=true
      options: --verbose
      meson-version: 0.53.2
      ninja-version: 1.9.0.post1
      gcovr-version: 4.2
